function data()
return {
	en = {
		["mod_name"] = "Construction train cars",
		["mod_desc"] = "Various wagons for use in construction trains for transport and ballast as well as for official use, for overnight stays or for longer stays of people e.g. on construction sites.",

        ["Bauzugwagen_menu"] = "Construction train (Facs | Fcs | Kbs | conversion cars)", 
        ["leer"] = " (empty)",
        ["halb"] = " (half loaded)",
        ["voll"] = " (full loaded)",
        ["Dienstwagen3yg_name"] = "Company car conversion car",
        ["Dienstwagen3yg_desc"] = "Retired 3-axle conversion wagons were continued to be used as railway service vehicles.",
        ["Werkstattwagen3yg_name"] = "Workshop car conversion car",
        ["Werkstattwagen3yg_desc"] = "Retired 3-axle conversion wagons were continued to be used as railway service vehicles.",
        ["Facs124_bauzug_name"] = "Facs 124 Construction train DB AG",
        ["Facs124_bauzug_desc"] = "Type Facs 124 self-unloading wagon with gravity discharge in yellow as a Deutsche Bahn AG construction train. Unloaded, half full or fully loaded with track ballast.",        
        ["Fcs090_wiebe_name"] = "Fcs 090 Wiebe",
        ["Fcs090_wiebe_desc"] = "Type Facs 124 self-unloading wagon with gravity discharge in yellow as of Deutsche Bahn AG construction train. Unloaded, half full or fully loaded with track ballast.",
        ["Fcs090_OeBB_name"] = "Fcs 090 ÖBB Infrastruktur",
        ["Fcs090_OeBB_desc"] = "Type Fcs 090 self-unloading wagon with gravity discharge in ÖBB Infrastructure livery. Unloaded, half full or fully loaded with track ballast.",
        ["Fcs090_gleisbau_name"] = "Fcs 090 Gleisbau",
        ["Fcs090_gleisbau_desc"] = "Fcs 090 type self-unloading wagon with gravity discharge in the colour scheme of the company Hering Gleisbau. Unloaded, half full or fully loaded with track ballast.",
        ["Kbs442_bauzug_name"] = "Kbs 442 Rungenwagen DB",
        ["Kbs442_bauzug_dbag_name"] = "Kbs 442 Rungenwagen DB AG",
        ["Kbs442_bauzug_desc"] = "Stake wagon with plugged stakes type Kbs 442. Unloaded or loaded with wheelsets.",
        ["Kls442_bauzug_name"] = "Kls 442 Rungenwagen DB",
        ["Kls442_bauzug_dbag_name"] = "Kls 442 Rungenwagen DB AG",
        ["Kls442_bauzug_desc"] = "Kls 442 type stake wagon without stakes. Unloaded or loaded with track ballast.",
	},
	de = {
		["mod_name"] = "Bauzugwagen",
		["mod_desc"] = "Verschiedene Wagen für den Einsatz in Bauzügen zum Transport und Schotter sowie zum Dienstgebrauch, zur Übernachtung oder zum längeren Aufenthalt von Personen z.B. auf Baustellen.",

        ["Bauzugwagen_menu"] = "Bauzug (Facs | Fcs | Kbs | Dienstwagen)", 
        ["leer"] = " [unbeladen]",
        ["halb"] = " [halb beladen]",
        ["voll"] = " [voll beladen]",
        ["Dienstwagen3yg_name"] = "Dienstwagen Umbauwagen",
        ["Dienstwagen3yg_desc"] = "Ausgemusterte 3-achsige Umbauwagen wurden als Bahndienstwagen weitergenutzt.",
        ["Werkstattwagen3yg_name"] = "Werkstattwagen Umbauwagen",
        ["Werkstattwagen3yg_desc"] = "Ausgemusterte 3-achsige Umbauwagen wurden als Bahndienstwagen weitergenutzt.",
        ["Facs124_bauzug_name"] = "Facs 124 Bauzug DB AG",
        ["Facs124_bauzug_desc"] = "Selbstentladewagen mit Schwerkraftentleerung der Bauart Facs 124 in gelb als Bauzug der Deutschen Bahn AG. Unbeladen, halb voll beladen oder voll beladen mit Gleisschotter.",        
        ["Fcs090_wiebe_name"] = "Fcs 090 Wiebe",
        ["Fcs090_wiebe_desc"] = "Selbstentladewagen mit Schwerkraftentleerung der Bauart Fcs 090 in braun als Bauzug der Firma H.F. Wiebe. Unbeladen, halb voll beladen oder voll beladen mit Gleisschotter.",
        ["Fcs090_OeBB_name"] = "Fcs 090 ÖBB Infrastruktur",
        ["Fcs090_OeBB_desc"] = "Selbstentladewagen mit Schwerkraftentleerung der Bauart Fcs 090 in Farbgebung der ÖBB Infrastruktur. Unbeladen, halb voll beladen oder voll beladen mit Gleisschotter.",
        ["Fcs090_gleisbau_name"] = "Fcs 090 Gleisbau",
        ["Fcs090_gleisbau_desc"] = "Selbstentladewagen mit Schwerkraftentleerung der Bauart Fcs 090 in Farbgebung der Firma Hering Gleisbau. Unbeladen, halb voll beladen oder voll beladen mit Gleisschotter.",
        ["Kbs442_bauzug_name"] = "Kbs 442 Rungenwagen DB",
        ["Kbs442_bauzug_dbag_name"] = "Kbs 442 Rungenwagen DB AG",
        ["Kbs442_bauzug_desc"] = "Rungenwagen mit gesteckten Rungen der Bauart Kbs 442. Unbeladen oder beladen mit Radsätzen.",
        ["Kls442_bauzug_name"] = "Kls 442 Rungenwagen DB",
        ["Kls442_bauzug_dbag_name"] = "Kls 442 Rungenwagen DB AG",
        ["Kls442_bauzug_desc"] = "Rungenwagen ohne Rungen der Bauart Kls 442. Unbeladen oder beladen mit Gleisschotter.",
	}
}
end
